
const courseNameMapping = {
    "MATEMATICA I": "Matemática I",
    "INTRODUCCION DE CIENCIA DE LA COMPUTACION": "Introducción de Ciencia de la Computación",
    "CIENCIA DE LA COMPUTACION II": "Ciencia de la Computación II",
    "ESTADISTICA Y PROBABILIDADES": "Estadística y Probabilidades",
    "PROGRAMACION DE VIDEO JUEGOS": "Programación de Videojuegos",
    "CIENCIA DE LA COMPUTACION I": "Ciencia de la Computación I",
    "APRECIACION MUSICAL": "Apreciación Musical",
    "INTRODUCCION A LA FILOSOFIA": "Introducción a la Filosofía",
    "INGENIERIA DE SOFTWARE III": "Ingeniería de Software III",
    "DESARROLLO BASADO EN PLATAFORMAS": "Desarrollo Basado en Plataformas",
    "MATEMATICA II": "Matemática II",
    "ANALISIS Y DISENO DE ALGORITMOS": "Análisis y Diseño de Algoritmos",
    "TEORIA DE LA COMPUTACION": "Teoría de la Computación",
    "FORMACION DE EMPRESAS DE BASE TECNOLOGICA II": "Formación de Empresas de Base Tecnológica II",
    "INTERACCION HUMANO COMPUTADOR": "Interacción Humano-Computador",
    "ALGORITMOS Y ESTRUCTURAS DE DATOS": "Algoritmos y Estructuras de Datos",
    "MORAL": "Moral",
    "LIDERAZGO": "Liderazgo",
    "LENGUAJES DE PROGRAMACION": "Lenguajes de Programación",
    "TEATRO": "Teatro",
    "CALCULO II": "Cálculo II",
    "ARQUITECTURA DE COMPUTADORES": "Arquitectura de Computadores",
    "HISTORIA DE LA CIENCIA Y TECNOLOGIA": "Historia de la Ciencia y Tecnología",
    "ROBOTICA": "Robótica",
    "APRECIACION LITERARIA": "Apreciación Literaria",
    "INTRODUCCION A LA VIDA UNIVERSITARIA": "Introducción a la Vida Universitaria",
    "ESTRUCTURAS DISCRETAS II": "Estructuras Discretas II",
    "ESTRUCTURAS DE DATOS AVANZADAS": "Estructuras de Datos Avanzadas",
    "TEOLOGIA": "Teología",
    "ETICA PROFESIONAL": "Ética Profesional",
    "APRECIACION ARTISTICA": "Apreciación Artística",
    "HISTORIA DE LA CULTURA": "Historia de la Cultura",
    "PROGRAMACION COMPETITIVA": "Programación Competitiva",
    "ANTROPOLOGIA FILOSOFICA Y TEOLOGICA": "Antropología Filosófica y Teológica",
    "COMPUTACION GRAFICA": "Computación Gráfica",
    "METODOLOGIA DEL ESTUDIO": "Metodología del Estudio",
    "ENSENANZA SOCIAL DE LA IGLESIA": "Enseñanza Social de la Iglesia",
    "CALCULO I": "Cálculo I",
    "ESTRUCTURAS DISCRETAS I": "Estructuras Discretas I",
    "ANALISIS DE LA REALIDAD PERUANA": "Análisis de la Realidad Peruana",
    "ALGEBRA ABSTRACTA": "Álgebra Abstracta",
    "PERSONA, MATRIMONIO Y FAMILIA": "Persona, Matrimonio y Familia",
    "COMPILADORES": "Compiladores",
    "COMPUTACION EN LA SOCIEDAD": "Computación en la Sociedad",
    "ANALISIS NUMERICO": "Análisis Numérico",
    "BIG DATA": "Big Data",
    "BASES DE DATOS II": "Bases de Datos II",
    "METODOLOGIA DE LA INVESTIGACION EN COMPUTACION": "Metodología de la Investigación en Computación",
    "MATEMATICA APLICADA A LA COMPUTACION": "Matemática Aplicada a la Computación",
    "INTELIGENCIA ARTIFICIAL": "Inteligencia Artificial",
    "PROYECTO FINAL DE CARRERA II": "Proyecto Final de Carrera II",
    "COMUNICACION": "Comunicación",
    "ORATORIA": "Oratoria",
    "FORMACION DE EMPRESAS DE BASE TECNOLOGICA I": "Formación de Empresas de Base Tecnológica I",
    "PROYECTO FINAL DE CARRERA III": "Proyecto Final de Carrera III",
    "COMPUTACION MOLECULAR BIOLOGICA": "Computación Molecular Biológica",
    "INGENIERIA DE SOFTWARE II": "Ingeniería de Software II",
    "BASES DE DATOS I": "Bases de Datos I",
    "FISICA COMPUTACIONAL": "Física Computacional",
    "TOPICOS AVANZADOS EN INGENIERIA DE SOFTWARE": "Tópicos Avanzados en Ingeniería de Software",
    "CLOUD COMPUTING": "Cloud Computing",
    "TOPICOS EN INTELIGENCIA ARTIFICIAL": "Tópicos en Inteligencia Artificial",
    "TOPICOS EN COMPUTACION GRAFICA": "Tópicos en Computación Gráfica",
    "COMPUTACION PARALELA Y DISTRIBUIDA": "Computación Paralela y Distribuida",
    "REDES Y COMUNICACION": "Redes y Comunicación",
    "SISTEMAS OPERATIVOS": "Sistemas Operativos",
    "INGENIERIA DE SOFTWARE I": "Ingeniería de Software I",
    "PROYECTO FINAL DE CARRERA I": "Proyecto Final de Carrera I",
    "INGLES TECNICO PROFESIONAL": "Inglés Técnico Profesional",
    "SEGURIDAD EN COMPUTACION": "Seguridad en Computación",
    "SISTEMAS DE INFORMACION": "Sistemas de Información"
};

export const formatCourseName = (name) => {
    if (!name) return '';
    const upperName = name.toUpperCase().trim();
    return courseNameMapping[upperName] || name; // Fallback to original if not found
};
